apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: "cluster-issuer"
spec:
  ingressClassName: traefik
  rules:
    - host: argo.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argo-bridge
                port:
                  number: 443
  tls:
    - hosts:
        - argo.internal
      secretName: tls-argo
---
apiVersion: v1
kind: Service
metadata:
  name: argo-bridge  # In ingress namespace
spec:
  type: ExternalName
  externalName: argocd-server.argocd.svc.cluster.local  # Full FQDN of target service
  ports:
    - port: 443
      targetPort: 443