cert-manager: 
  crds:
    enabled: true
  config:
    featureGates:
      ACMEHTTP01IngressPathTypeExact: false
    
acmeServer: "https://acme-v02.api.letsencrypt.org/directory"

ingress:
  className: "nginx"

issuer:
  selfSigned: false
  email: "dev@ollimart.in"
