pihole:
#  dnsmasq:
#    customDnsEntries:
#      - address=/vault.internal/10.5.0.100

  persistentVolumeClaim:
    enabled: false
    
  replicaCount: 3
    
  # No DNS used here, just pointing to cluster-internal service ips
  podDnsConfig:
    enabled: false
  
  admin:
    enabled: false

  serviceDns:
    type: NodePort
    port: 5353
    
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  extraEnvVars:
    FTLCONF_dns_listeningMode: SINGLE
    FTLCONF_misc_dnsmasq_lines: |
      address=/.internal/10.5.0.100