pihole:
  persistentVolumeClaim:
    enabled: false
    
  replicaCount: 3
    
  # No DNS used here, just pointing to cluster-internal service ips
  podDnsConfig:
    enabled: false
  
  admin:
    enabled: false

  serviceDns:
    type: LoadBalancer
    loadBalancerIP: 10.43.100.100
    
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  extraEnvVars:
    FTLCONF_misc_dnsmasq_lines: |
      address=/.internal/10.5.0.100