apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dns-external
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20" # Depends on cert-manager
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    helm:
      valueFiles:
        - values.yaml
    path: git-ops/dns-external
    repoURL: https://github.com/OlliMartin/home-lab
    targetRevision: main
  destination:
    name: 'in-cluster'
    namespace: dns-external
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
